In [1]:
import numpy as np

In [2]:
my_list = [10, 20, 30, 40, 50, 60]

In [5]:
my_numpy_array = np.array(my_list)
type(my_numpy_array)

numpy.ndarray

In [7]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [8]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [9]:
np.random.random(5)

array([0.91916126, 0.28759202, 0.98965459, 0.36139282, 0.91187466])

In [17]:
list1 = [1, 5, 9]
list2 = [2, 4, 8]
list1 + list2

[1, 5, 9, 2, 4, 8]

In [18]:
np_list1 = np.array(list1)
np_list2 = np.array(list2)
np_list1 + np_list2

array([ 3,  9, 17])

In [14]:
# Listelerde toplama yapınca elemanlar birleşirken, numpy'da toplama işlemi matrix şeklinde olur.

In [25]:
list1 * 3
# Listeyi 3 kez yazdırır

[1, 5, 9, 1, 5, 9, 1, 5, 9]

In [26]:
np_list1 * 3
# Liste elemanlarını 3le çarpar

array([ 3, 15, 27])

In [31]:
np_arrayI = np.arange(0, 20, 2)
np_arrayI

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [32]:
np_arrayI[0]

np.int64(0)

In [33]:
np_arrayI[-1]

np.int64(18)

In [34]:
np_arrayI[::-1]

array([18, 16, 14, 12, 10,  8,  6,  4,  2,  0])

In [35]:
np.random.randn(4,4)

array([[ 0.14974101,  0.50062335,  0.7141183 ,  0.13151312],
       [ 0.11369952,  0.95053213, -0.96284566, -0.38623691],
       [-0.22206289, -0.033678  ,  0.5651092 ,  1.811369  ],
       [-0.44368208,  0.12321147, -0.07193053,  0.86604367]])

In [36]:
np.random.randint(1,300,5)

array([164, 240, 237, 232, 215])