In [1]:
import numpy as np

In [2]:
np_matrix = np.array([[5,10],[15,20]])

In [3]:
np_matrix

array([[ 5, 10],
       [15, 20]])

In [4]:
np_matrix.sum()

np.int64(50)

In [5]:
np.random.random((3,2))

array([[0.87764817, 0.27554727],
       [0.73924963, 0.09885856],
       [0.23905655, 0.39626634]])

In [6]:
first_arr = np.array([[10,20], [30,40]])
second_arr = np.array([[5,15], [25,35]])

In [7]:
first_arr

array([[10, 20],
       [30, 40]])

In [8]:
second_arr

array([[ 5, 15],
       [25, 35]])

In [9]:
third_arr = np.array([[50], [60]])

In [10]:
third_arr

array([[50],
       [60]])

In [11]:
third_arr.shape

(2, 1)

In [18]:
first_arr @ second_arr

array([[ 550,  850],
       [1150, 1850]])

In [19]:
f_matrix = np.array([[10, 20, 30]])
s_matrix = np.array([[2,3],[2,3],[2,3]])

In [20]:
f_matrix.shape

(1, 3)

In [21]:
s_matrix.shape

(3, 2)

In [22]:
f_matrix.dot(s_matrix)

array([[120, 180]])

In [23]:
neww = np.random.randint(1, 100, 20)

In [24]:
neww

array([ 2, 56, 40, 72, 34, 84, 12, 61, 33, 99, 79, 45, 35, 45, 56, 11, 92,
       10, 13, 35])

In [25]:
neww > 25

array([False,  True,  True,  True,  True,  True, False,  True,  True,
        True,  True,  True,  True,  True,  True, False,  True, False,
       False,  True])

In [26]:
trans_arr = np.array([[10,20],[30,40],[50,60]])

In [27]:
trans_arr

array([[10, 20],
       [30, 40],
       [50, 60]])

In [28]:
trans_arr.shape

(3, 2)

In [29]:
trans_arr.transpose()

array([[10, 30, 50],
       [20, 40, 60]])

In [30]:
data = np.array([10,15,17,20,25,26,28,30,32,40,45,70,76,80,100])

In [34]:
mean = np.mean(data)
mean # Ortalama

np.float64(40.93333333333333)

In [36]:
std = np.std(data)
std # Standart Sapma

np.float64(26.57183136748806)

In [38]:
z_scores = (data - mean) / std
z_scores

array([-1.16414006, -0.97597087, -0.90070319, -0.78780168, -0.59963249,
       -0.56199865, -0.48673097, -0.4114633 , -0.33619562, -0.03512492,
        0.15304427,  1.09389023,  1.31969326,  1.47022861,  2.22290537])

In [39]:
# Math Problemi çözmek

In [40]:
# 2x + 3y = 8 ve 5x + 7y = 19 olsun

In [42]:
A = np.array([[2,3],[5,7]]) # Kat sayılar

In [43]:
b = np.array([8,19]) # Sonuçlar

In [45]:
sol = np.linalg.solve(A,b)
sol

array([1., 2.])